### ISSUE TITLE
Bootstrap Helm installation 

### ISSUE THREAD

**Issue by afzal442** [ortelius/ortelius-charts#12]
Getting `CrashLoopBackOff` error

```
NAME                                READY   STATUS             RESTARTS      AGE
db-load-8x6n9                       1/1     Running            0             3m1s
express-server-78d668c9bc-h69rc     1/1     Running            0             21d
ms-compitem-crud-6877499cf5-hqvsl   1/1     Running            0             3m1s
ms-dep-pkg-cud-64f677ff8-fwcl7      1/1     Running            0             3m1s
ms-dep-pkg-r-86b565b988-dxrpt       1/1     Running            0             3m1s
ms-general-6b845f65c9-f25tg         1/1     Running            0             3m
ms-nginx-7b6f68d8f9-tznvn           1/1     Running            0             3m1s
ms-scorecard-767975d67c-286xq       0/1     CrashLoopBackOff   4 (78s ago)   3m
ms-textfile-crud-59cb9947bc-2j99h   1/1     Running            0             3m
ms-ui-5d5b99fff9-qdp6c              1/1     Running            0             3m
ms-validate-user-6fd5d95f9-88gkx    1/1     Running            0             3m1s
```

after following these installations 
```
helm repo add ortelius https://ortelius.github.io/ortelius-charts/
helm install my-release ortelius/ortelius --set ms-general.dbpass=my_db_password --set ms-nginx.ingress.type=ssloff --set ms-general.dbhost=orteliusdb.us-east-1.rds.amazonaws.com
```
LMK if anyone has encountered this kind of trouble. `Error: failed to create containerd task: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "/app/uvicorn": stat /app/uvicorn: no such file or directory: unknown` 

Thanks

cc @sbtaylor15

**Comment by sbtaylor15** [comment]
@afzal442 The scorecard image has been fixed.  Please use helm chart version 10.0.280 and upgrade your cluster.

**Comment by afzal442** [comment]
Hi I tried installing the helm chart by following this and it has spun up the cluster with the pods running stage.

` helm install my-ortelius ortelius/ortelius --version 10.0.280 --set ms-general.dbpass=my_db_password --set ms-nginx.ingress.type=ssloff --set ms-general.dbhost=orteliusdb.us-east-1.rds.amazonaws.com`

But when I Kubectl port forward, I am able to view the UI. It;s getting failed. After Kubectl describe I am gettin `Liveness probe failed: HTTP probe failed with statuscode: 503`

After some point of time, 
```
db-load-pkwvx                       1/1     Running            0               36m
ms-compitem-crud-59cc9555d6-cvd54   0/1     CrashLoopBackOff   7 (3m58s ago)   36m
ms-dep-pkg-cud-5cd5595bbd-5ql5t     0/1     CrashLoopBackOff   7 (3m58s ago)   36m
ms-dep-pkg-r-5f46b855f5-xwvmq       0/1     CrashLoopBackOff   7 (3m57s ago)   35m
ms-general-6b845f65c9-5sbh7         1/1     Running            0               35m
ms-nginx-7b6f68d8f9-qnvdw           1/1     Running            0               36m
ms-scorecard-67d5b6ffb9-wtc75       0/1     CrashLoopBackOff   7 (3m58s ago)   35m
ms-textfile-crud-59cb9947bc-sg2xp   0/1     CrashLoopBackOff   7 (3m58s ago)   36m
ms-ui-5d5b99fff9-r959m              1/1     Running            0               35m
ms-validate-user-6fd5d95f9-sqsm8    0/1     CrashLoopBackOff   7 (3m58s ago)   36m
```

**Comment by sbtaylor15** [comment]
@afzal442 Postgres has ssl enabled by default on AWS. Please add `--set "ms-general.dhname=postgres?ssl=true"`.  Let me know if that solves the issue.

**Comment by afzal442** [comment]
Thanks again. That resolves the pods being CrashLoopBackOff, but UI doesn't comes up. The logs say as below:

```
+ '[' OFF '=' ON ]
+ '[' OFF '=' OFF ]
+ echo 'Turn SSL Off'
+ cp /etc/nginx/nginx-nossl.conf /etc/nginx/nginx.conf
Turn SSL Off
+ '[' default '!='  ]
+ sed -i.bak s/default.svc.cluster.local/default.svc.cluster.local/ /etc/nginx/nginx.conf
+ nginx -g 'daemon off;'
[18/Apr/2023:02:02:03 +0000] 127.0.0.1 to: 10.128.236.74:8080: GET / HTTP/1.1 upstream_response_time 0.083 msec 1681783323.656 request_time 0.083
2023/04/18 02:02:03 [error] 9#9: *1 open() "/var/www/favicon.ico" failed (2: No such file or directory), client: 127.0.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", host: "localhost:8080", referrer: "http://localhost:8080/"
[18/Apr/2023:02:02:03 +0000] 127.0.0.1 to: -: GET /favicon.ico HTTP/1.1 upstream_response_time - msec 1681783323.787 request_time 0.000
2023/04/18 02:03:04 [error] 9#9: *3 upstream timed out (110: Operation timed out) while reading response header from upstream, client: 127.0.0.1, server: localhost, request: "GET /dmadminweb/Home HTTP/1.1", upstream: "http://10.128.236.74:8080/dmadminweb/Home", host: "localhost:8080", referrer: "http://localhost:8080/"
```

**Comment by sbtaylor15** [comment]
@afzal442 How are you running Ortelius, in a Kind Cluster?  Are you using Kubernetes proxy to access Ortelius UI?

**Comment by afzal442** [comment]
Sorry @sbtaylor15 ! I am using `Linode` Cluster. I am not sure abt using Kubernetes proxy here.

**Comment by sbtaylor15** [comment]
@afzal442  Run `kubectl get ingress -A` and post the output.  We need to see if the ingress is up and running correctly.

**Comment by afzal442** [comment]
her you go!

```
kubectl get ingress -A
NAMESPACE   NAME       CLASS   HOSTS   ADDRESS   PORTS   AGE
default     ms-nginx   nginx   *                 80      2m11s

```

**Comment by sbtaylor15** [comment]
@afzal442 Can you please send me the info on how you setup your Linode Cluster?  It looks like the Ingress is not resolving an Address that routes the host traffic into the Ortelius service.

**Comment by afzal442** [comment]
Thanks for that. I followed this https://www.linode.com/docs/products/compute/kubernetes/get-started/#create-an-lke-cluster

![image](https://user-images.githubusercontent.com/11625672/233231968-66a9d2f0-5a62-44ad-a2b7-bf77aaf8a975.png)

**Comment by afzal442** [comment]
However, I tried out [killercoda](https://killercoda.com/playgrounds/scenario/kubernetes) environment, I still failed to capture. Could you tell me how do you set up?

```
helm install my-ortelius ortelius/ortelius --version 10.0.280 --set ms-general.dbpass=my_db_password --set ms-nginx.ingress.type=ssloff --set ms-general.dbhost=orteliusdb.us-east-1.rds.amazonaws.com --set "ms-general.dhname=postgres?ssl=true"
```

Then, `k port-forward svc/ms-nginx 8080:80`

**Comment by sbtaylor15** [comment]
@afzal442 we have added additional setup instructions in the [helm chart readme ](https://artifacthub.io/packages/helm/ortelius/ortelius) for:
* Kind Cluster
* k3s on KillerCoda
* GKE
* EKS

We were not able to get the ingress to work correctly under the Killercoda Kubernetes playground.  It will work on Killercoda Ubuntu under K3S.  

Please use 10.0.310 of the helm chart.

**Comment by afzal442** [comment]
Hi @sbtaylor15 I tried out `k3s on KillerCoda` pg. It didn't work for me. Could you look into that? The scenario for this is https://killercoda.com/k3s/

```
Error: INSTALLATION FAILED: Kubernetes cluster unreachable: Get "http://localhost:8080/version": dial tcp 127.0.0.1:8080: connect: connection refused
```

**Comment by sbtaylor15** [comment]
@afzal442 we have updated the [instructions for Killercoda](https://artifacthub.io/packages/helm/ortelius/ortelius#installing-on-kubernetes-on-killercoda).  Basically, you will need to use a nodePort and then access the UI using the nodePort in the Killercoda Traffic/Ports page.  See the instructions for details.

**Comment by bradmccoydev** [comment]
Hi @afzal442 can this be closed now?

**Comment by afzal442** [comment]
Sorry @bradmccoydev, Still investigating. I will close it as soon as I get it.

**Comment by afzal442** [comment]
Thanks to @sbtaylor15 for making it up after tinkering around it. I thought of documenting as part of blogathon. BTW we can create a killercoda lab exercise for this like [falco](https://killercoda.com/falco). 😉

**Comment by sbtaylor15** [comment]
@afzal442 please create a new issue in the [ortelius/ortelius](https://github.com/ortelius/ortelius/issues) repo for the doc updates.  That repo is where we keep all of the issues for easy management.
