### ISSUE TITLE
Ortelius chart version 10.0.336 does not exist

### ISSUE THREAD

**Issue by agardnerIT** [ortelius/ortelius-charts#13]
Instructions need to be update for latest chart version:

`ORTELIUS_VERSION=10.0.336` -> `ORTELIUS_VERSION=10.0.462`

**Comment by sbtaylor15** [comment]
@agardnerIT Can you see if there is a way to dynamically update the version numbers?  Maybe a badge url

**Comment by sbtaylor15** [comment]
Added code to main.js to update the version number as part of the build
